version: "3"
services:
  db:
    image: postgres:10.2-alpine
    container_name: log_lady-db
    environment:
      - POSTGRES_PASSWORD=postgres 
      - POSTGRES_DB=log_lady_prod
    networks:
      - nginx-network
  admin:
    image: log_lady-release
    container_name: log_lady-admin
    build:
      context: .
      dockerfile: Dockerfile.run
    command: 
      - eval
      - LogLady.ReleaseTasks.seed
    networks:
      - nginx-network
    depends_on:
      - db
  server:
    image: log_lady-release
    container_name: log_lady-server
    environment:
      - PORT=5000
      - HOST=logladyapi.fakeshrimp.com
    expose:
      - "5000"
    command: start
    networks:
      - nginx-network
    depends_on:
      - db
      - admin
networks:
  nginx-network:
    external: true
