version: "3"
services:
  server:
    image: nginx:1.21.1-alpine
    container_name: nginx-server
    ports:
      - "80:80"
    volumes:
      - ./conf.d:/etc/nginx/conf.d:ro
      - /var/www/log_lady_fe:/var/www/log_lady_fe
    networks:
      - nginx-network
networks:
  nginx-network:
    external: true
